rules:
  no-css-comments: 0
  placeholder-in-extend: 0
  nesting-depth: 0
  no-duplicate-properties: 0
  property-sort-order:
    - 1
    -
      order: concentric
  class-name-format:
    - 1
    -
      convention: hyphenatedbem
